name: CratesReloaded
main: BajanVlogs\SuperCrates\Main
version: 1.0.0-B1
api: 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0ALPHA11
load: POSTWORLD
author: VMPE Development Team
description: Custom crates that will make your server better than ever

commands:
  givekey:
    description: Give key to player
  setcrate:
    description: Set the location a block
